#!/Users/schacon/otp_src_R13B03/bin/escript
%% -*- erlang -*-
%%! debug verbose -noshell

main([Object]) ->
    geef:start(),
    Test = geef:object_exists(4),
    io:format("exists ~s:~w~n", [Object, Test]);
main(_) ->
    usage().
        
usage() ->
    io:format("usage: ./test SHA\n"),
    halt(1).
        
